# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

cache:
  paths:
  - ".cache/pip"
  - venv/
before_script:
- python --version
- echo $TAG_LATEST
- pip install poetry
- poetry install
- poetry
run:
  script:
  - poetry build
  - pip install dist/*.whl
  - ip-reveal-headless get-all
  - poetry config pypi-token.pypi $PYPI_TOKEN
  - poetry publish
  artifacts:
    paths:
    - dist/*.whl
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
